### ISSUE TITLE
[Feature Request] Import chunks above a certain height

### ISSUE THREAD

**Issue by carthradge4** [Querz/mcaselector#114]
Hi, I'm part of a large server online and we're seeing what the best way to reset the Nether is. We want to keep the very extensive ice roads we have on the Nether roof. This tool is amazing and almost does what we need, so I wanted to check regarding this feature request.

Would it be feasible to make an option when importing chunks to only import blocks above a certain height? That way we can manually regenerate an area and then easily import only the Nether highway. This would save a lot of people a lot of time with the new Nether update coming up.

**Comment by Querz** [comment]
This can work, but there's a huge problem with version compatibility. Example:
A chunk with DataVersion 2201 is not compatible with a chunk that has DataVersion 2203, because 2201 still uses biome columns (256 biomes per chunk, 1 biome from top to bottom) while 2203 uses 3D biomes (1024 biomes per chunk, in 4x4x4 blocks).
I could make something like this work, but only if both chunks are exactly the same version. Otherwise it would be a giant mess to make everything forward and backward compatible. Compatibility between different versions work right now because they are on the chunk level, and the game handles all conversions to newer versions on its own.

There is an alternative solution already discussed [here](https://github.com/Querz/mcaselector/issues/103#issuecomment-636043116). Basically you can delete all sections of a chunk up to y=128 and then set the Status to "empty" using the NBT Changer tool. Problem with this is though that sometimes there is still stuff generated above y=128 (mushrooms / fungi trees of the new biomes) which could then interfere with your Nether highway, but it would still be the safest bet right now.

**Comment by carthradge4** [comment]
Thanks. I'd be happy to test anything you get to make. It seems that we can use the method to delete everything under the Nether roof as a fallback, but we'd like to be able to keep some structures under the Nether roof if that's a possibility, while still allowing most of that area to regenerate.

**Comment by Querz** [comment]
Sorry for the long wait.
I put some stuff together:
* Added a "Range"-field to the import configuration dialog. Syntax is `<from>:<to>`. E.g. if you want to import sections 0 to 8, it's `0:8`.
* Sections, Entities, TileEntities, TileTicks, LiquidTicks, Structures and Biomes (for 3D Biomes). Still missing Lights, LiquidsToBeTicked, ToBeTicked and PostProcessing, but it should be enough for basic testing.

I tested everything in Minecraft 1.16-pre5. As far as I can tell, it works, but Minecraft does some weird stuff with biomes (at least in 1.16-pre5).
As an example I successfully imported sections 5-15 from a Nether chunk into the Overworld (including offset). Judging from the raw biome data in the mca file, the biomes are imported correctly, but Minecraft's F3 screen only shows the Nether biomes if the entire chunk is made of Nether biomes. The Nether biomes remain correct in the file though, Minecraft doesn't change them even after saving the file.

Here's a compiled test version you can try:
[mcaselector-1.10.1-pre-section-import.jar.zip](https://github.com/Querz/mcaselector/files/4775582/mcaselector-1.10.1-pre-section-import.jar.zip)

**Comment by carthradge4** [comment]
Amazing! we'll try it

**Comment by carthradge4** [comment]
I noticed something funky going on with the 1.10 version vs 1.9. For the same world, the new version is not showing all chunks correctly:

https://imgur.com/a/h79jNus

Is this a known issue?

**Comment by Querz** [comment]
That is indeed not correct.

Could you upload one of those region files that render differently in the preview version? Thanks!

**Comment by Querz** [comment]
I think I found the issue, alongside a bug in the debug code.

Apparently when you optimize your world (using the "Optimize World" button in Minecraft), it fills empty chunks with some weird stuff:

* TileEntities, Entities and Sections become empty LongArrayTags
* Status is set to `structure_starts`

If you don't mind I still would like to have a look at one of your region files to make sure that that's it.

**Comment by carthradge4** [comment]
Sorry for the delay, some personal issues came up. I really appreciate everything you've done. Here is an example set of chunks that don't show up in the 1.10 version (Nether):

https://www.dropbox.com/s/ak2g75g7tlefct7/r.0.-2.mca?dl=0

**Comment by Querz** [comment]
The file does not contain any more chunks than a small strip from 0|-64 to 0|-33. I fixed a bug though where it didn't show the nether correctly for Minecraft 1.13 versions.

**Comment by carthradge4** [comment]
Thank you, wanted to confirm that it's working on 1.12. The small strip was intended to keep the file size small. It wasn't showing up in the 1.10 version but it works now.
