### ISSUE TITLE
App does not use OS cache directories

### ISSUE THREAD

**Issue by strugee** [Querz/mcaselector#127]
**Describe the bug**

When storing cached data, the app doesn't use the operating system's cache directory. As far as I can tell based on this code: https://github.com/Querz/mcaselector/blob/62edae96d094f3422671a2e938944cf9b128ff47/src/main/java/net/querz/mcaselector/Config.java#L33 instead a directory called `cache` is created and used in the same location the JAR is running from.

This is a problem in Flatpak builds (#126) because `/app/bin`, where the JAR is installed to, is mounted read-only so I get like 100 lines of stack trace when the app tries to store something to cache.

**To Reproduce**

N/A

**Expected behavior**

Based on https://github.com/Querz/mcaselector#caching it seems like this data really is a pure cache, in that it can be deleted any time without any adverse impact (besides performance). If that's accurate, it should store this data at `~/Library/Caches/MCA Selector` on macOS and `$XDG_CACHE_DIR/mcaselector` on Linux, where if `$XDG_CACHE_DIR` is not set in the environment it is defaulted to `~/.cache`.

See https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW1 for Apple documentation and https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html for the Linux cache directory specification.

**Screenshots and other files**

N/A

**Environment (please complete the following information):**
- OS: Linux ([Flatpak](https://flatpak.org/)'s `org.gnome.Platform` runtime, version 3.36, with the `org.freedesktop.Sdk.Extension.openjdk11` SDK extension applied)
- Java version: `openjdk 11.0.7 2020-04-14`
- Version 1.12

**Additional context**

N/A

**Comment by Querz** [comment]
I made some changes [here](https://github.com/Querz/mcaselector/blob/os-cache/src/main/java/net/querz/mcaselector/Config.java#L38) to accomodate for this. I also changed the directories on other platforms accordingly:

* Windows:
  * Cache directory: `%LOCALAPPDATA%\mcaselector\cache` if `%LOCALAPPDATA%` is set, otherwise `<parent directory of mcaselector.jar>\mcaselector\cache`
  * Log file: `%LOCALAPPDATA%\mcaselector\debug.log` if `%LOCALAPPDATA%` is set, otherwise `<parent directory of mcaselector.jar>\mcaselector\debug.log`
  * Config file: `%LOCALAPPDATA%\mcaselector\settings.ini` if `%LOCALAPPDATA%` is set, otherwise `<parent directory of mcaselector.jar>\mcaselector\settings.ini`
* MacOS:
  * Cache directory: `~/Library/Caches/mcaselector`
  * Log file: `~/.log/mcaselector/debug.log`
  * Settings file: `~/Library/Application Support/mcaselector/settings.ini`
* Linux:
  * Cache directory: `$XDG_CACHE_DIR/mcaselector` if `$XDG_CACHE_DIR` is set, otherwise `~/.cache/mcaselector`
  * Log file: `~/.log/mcaselector/debug.log`
  * Config file: `~/.mcaselector`

There are also temporary files when importing chunks or changing data, but those are all covered by `File.createTempFile()`.

**Comment by Querz** [comment]
Added in [release 1.12.1](https://github.com/Querz/mcaselector/releases/tag/1.12.1)

**Comment by strugee** [comment]
Nice, this is super helpful. Looks to me like some of those other paths need adjusting too though?

Windows seems fine although I don't really use Windows so I don't actually know. macOS log files are [apparently](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/MacOSXDirectories/MacOSXDirectories.html#//apple_ref/doc/uid/TP40010672-CH10-SW1) supposed to go in `~/Library/Logs`, but I can't remember if most apps actually did that from when I used macOS? So I dunno.

On Linux the log files, and any other data files (AFAICT mcaselector doesn't have any) should go in `$XDG_DATA_HOME/mcaselector/debug.log` (the last component of the path doesn't actually matter). `$XDG_DATA_HOME` defaults to `$HOME/.local/share` if unset or empty.

The config file should go in `$XDG_CONFIG_HOME/mcaselector/config` or `$HOME/.config/mcaselector/config` if the former variable is unset. Technically we're supposed to search `$XDG_CONFIG_DIRS` too (it's a `:`-delimited list of paths and there's a default in the spec) but this is much less important so like, if you don't feel like writing that code... eh, it's probably fine :P

If you're busy I can prepare a PR with these changes.

**Comment by Querz** [comment]
Thanks.
I also saw something about a `$XDG_CACHE_HOME` alongside `$XDG_CACHE_DIR`, is this in any way important?

**Comment by strugee** [comment]
Oof, I mixed up the variable names apparently. `$XDG_CACHE_HOME` is the right name, not `$XDG_CACHE_DIR`. :grimacing: so sorry!

**Comment by Querz** [comment]
I adjusted the default directories to comply with this specification, and they are now also working with the `$XDG_..._DIRS`.
It will first look at the `$XDG_..._HOME` value. If that is not set, It looks at all `$XDG_..._DIRS` values. If one of them already has cache files, the config file or a log file in there, it is used, otherwise it uses the first one. If `$XDG_..._DIRS` is not set, it uses `~/.cache/mcaselector` for cache files, `~/.local/share/mcaselector/debug.log` for the log file and `~/.mcaselector/mcaselector/settings.ini` for the config file.

I also adjusted the log file for MacOS to be `~/Library/Logs/mcaselector/debug.log`

See [release 1.12.2](https://github.com/Querz/mcaselector/releases/tag/1.12.2).

**Comment by Querz** [comment]
I fixed another bug in 1.12.3 where checking for environment variables on Windows would incorrectly split at `:`. Environment variables containing multiple paths on Windows are split using `;`.

To wrap this up, this is the current behaviour for cache, config and log files:

* Windows:
  * Cache directory: The first directory in `%LOCALAPPDATA%` containing `mcaselector\cache` or the first directory in `%LOCALAPPDATA%` plus `\mcaselector\cache` if `%LOCALAPPDATA%` is set, otherwise `<parent directory of mcaselector.jar>\mcaselector\cache`
  * Log file: The first directory in `%LOCALAPPDATA%` containing `mcaselector\debug.log` or the first directory in `%LOCALAPPDATA%` plus `\mcaselector\debug.log` if `%LOCALAPPDATA%` is set, otherwise `<parent directory of mcaselector.jar>\mcaselector\debug.log`
  * Config file: The first directory in `%LOCALAPPDATA%` containing `mcaselector\settings.ini` or the first directory in `%LOCALAPPDATA%` plus `\mcaselector\settings.ini` if `%LOCALAPPDATA%` is set, otherwise `<parent directory of mcaselector.jar>\mcaselector\settings.ini`
* MacOS:
  * Cache directory: `~/Library/Caches/mcaselector`
  * Log file: `~/Library/Logs/mcaselector/debug.log`
  * Settings file: `~/Library/Application Support/mcaselector/settings.ini`
* Linux:
  * Cache directory: `$XDG_CACHE_HOME/mcaselector` if `$XDG_CACHE_HOME` is set, otherwise the first directory containing a folder called `mcaselector` in `$XDG_CACHE_DIRS` or the first directory listed in `$XDG_CACHE_DIRS` plus `/mcaselector` if `$XDG_CACHE_DIRS` is set, otherwise `~/.cache/mcaselector`
  * Log file: `$XDG_DATA_HOME/mcaselector/debug.log` if `$XDG_DATA_HOME` is set, otherwise the first directory containing `mcaselector/debug.log` in `$XDG_DATA_DIRS` or the first directory listed in `$XDG_DATA_DIRS` plus `/mcaselector/debug.log` if `$XDG_DATA_DIRS` is set, otherwise `~/.local/share/mcaselector/debug.log`
  * Config file: `$XDG_CONFIG_HOME/mcaselector/settings.ini` if `$XDG_CONFIG_HOME` is set, otherwise the first directory containing `mcaselector/settings.ini` in `$XDG_CONFIG_DIRS` or the first directory in `$XDG_CONFIG_DIRS` plus `/mcaselector/settings.ini` if `$XDG_CONFIG_DIRS` is set, otherwise `~/.mcaselector/mcaselector/settings.ini`.

---

Temporary files are created using `File.createTempFile("name", null, null)`.

**Comment by strugee** [comment]
Wonderful, thanks! :tada:
