### ISSUE TITLE
Make at opinion to maximal zoom would not be restricted?

### ISSUE THREAD

**Issue by Matej-Hajek** [Querz/mcaselector#135]
If somebody has a big world, is good to see it all.

**Comment by Querz** [comment]
This would require some rework in how things are rendered. The performance can not increase too much either, because in order to render a region (no matter how far you zoomed out) requires to load the entire mca file anyway (because of compression).

If you have a regular 16:9 FullHD screen, you can see an area of approximately 200km² of your world. If you want a custom map and know a bit of programming, feel free to take a look at the [headless mode for generating the images](https://github.com/Querz/mcaselector#cache-images), then you can create use those images to create your own map.

If it's too big to move around, you can also use `View-->GoTo` to move to a specific location in your world.

**Comment by BanTheNons** [comment]
I'd also really like this. Isn't it better to give the user the freedom instead of disabling it for the sole purpose of performance? Unless there's another reason this wouldn't be feasible that I'm not seeing.
