### ISSUE TITLE
[SUGESTION] Change BIOME

### ISSUE THREAD

**Issue by gaRt3n** [Querz/mcaselector#14]
Could it be possible to implement Biome Changes?

**Comment by Querz** [comment]
It would be possible, but not the goal of this application.

Biomes are saved per-block-column, so there are 256 entries for biome data in each chunk. It could be possible to change the biome(s) of an entire chunk, but not the individual biome of each block column, because the UI (the top-down map view) only allows the selection of entire chunks and regions.

The NBT Changer is only meant to change data on chunk level, not block level.

The next version will add a new filter to select, export or delete chunks by their biomes.

**Comment by gaRt3n** [comment]
Oh well that would be enough to change it on the full file/Chunk :D since I got the problem that I generated a Nether world with OpenTerrainGenerator In 1.12 and after conversion to 1.13 all biomes got f***ed up and now I have normal mobs in Nether lol.

**Comment by Querz** [comment]
Yeah, I might implement it then. Just keep in mind that all operations with this tool are on chunk level, not on block level :)

**Comment by gaRt3n** [comment]
Thanks a bunch. You are helping me a lot here!

**Comment by To345** [comment]
hey, when could we expect that feature. im having to fill a lot of chunks with sand, so that the grass doesnt spoil the wasteland theme. i could really use that.

btw, can it be posible to import chunks or at least the block information?

**Comment by Querz** [comment]
I originally planned to release this together with the caching rework, but i guess i can split it up into two updates as the caching rework definitely takes some more time.

[Here's release 1.7](https://github.com/Querz/mcaselector/releases/tag/1.7) that adds this feature. Keep in mind that it changes the biomes of **the entire chunk** to one biome, it can't change the biome of individual block columns.
