### ISSUE TITLE
[Question] Which version should I use for beta 1.7.3 support

### ISSUE THREAD

**Issue by scamdotnet** [Querz/mcaselector#165]
Hi, I stumbled across MCA from the Minecraft wiki on mapping tools and programs. I found it because I needed a mapping tool that worked for beta 1.7.3. On the Minecraft wiki, it states that your tool supports Minecraft beta 1.3 - Release 1.16. When I try to load the world with the latest release on your releases tab, It doesn't do anything, no error messages at all, and it doesn't show anything on the map. I'm on macOS Big Sur if that helps.

**Comment by Querz** [comment]
MCA Selector does not support the old mcr format from before 1.2.1. I had a mix-up with the versions in the [Supported versions](https://github.com/Querz/mcaselector#supported-versions) section of the Readme a long while ago, and the info on Minecraft Wiki hasn't been updated yet.

The version mix-up was fixed in this commit: https://github.com/Querz/mcaselector/commit/9e528860ffb1ce53156fe3eec029dac2bc6c7455
