### ISSUE TITLE
Cant run app

### ISSUE THREAD

**Issue by Dufinetrz** [Querz/mcaselector#168]
I got last java and i cant run this program 

I cant run it

i got windows 10 
last java 

i cant open app so i cant reply to this

pls help

**Comment by Querz** [comment]
What have you tried so far? Do you get any error messages? What Java version are you using exactly? ("last java" is not a version and can literally change over night).

**Comment by Dufinetrz** [comment]
i only try to run it. No i didn't get error mesages.I got jre-8u281-windows-x64.exe i can open "open with" and then first is "java(TM) platform SE libary. Joust when i double click it nothing happen.

**Comment by Querz** [comment]
That looks like you downloaded the Java installer. You need to install Java first in order to use it.

Alternatively there is a temporary version for Windows that also contains a JRE on [the Discord](https://discord.com/channels/722924391805223113/722925054882742412/788093976111611904), just unpack it into an empty folder and run the `MCA Selector.exe`. I'm working on an installer for Windows that installs everything for your too, if you want to have a look at the [preview versions](https://discord.com/channels/722924391805223113/807350238783209514/813899169793310750).

**Comment by Dufinetrz** [comment]
When i click that link  it says "no text channels. You find yourself in a strange place.You dont hawe access to any text chanels , ore there is no one in this server" how i can join

**Comment by Querz** [comment]
[![chat](https://img.shields.io/discord/722924391805223113?logo=discord)](https://discord.gg/h942U8U)

**Comment by Dufinetrz** [comment]
i joined what now

**Comment by Dufinetrz** [comment]
i downloaded now i will try and say what happened

**Comment by Dufinetrz** [comment]
OMG it works thank you so mouch you are best querz!
