### ISSUE TITLE
Not clear how can I export certain chunks to another world

### ISSUE THREAD

**Issue by revolex** [Querz/mcaselector#17]
I have a 1.14 minecraft map, and i decided to add mods to oit, but first I have to go back in versions to 1.12 and export my progress to an 1.12 world file. I don't know how  should I do it, can I have some help?

**Comment by cr1st0ph3r** [comment]
I think that currently you cannot import extracted chunks into another world, but I think that this is a planned feature, so hopefully it will be implemented in the near future

**Comment by Querz** [comment]
As far as I know, Minecraft does not support importing world data from a newer version into an older version, especially not 1.13+ to 1.12 and neither does the MCA Selector.
Since version 1.7 you can import all chunks from another world into the currently opened world while specifying whether you want to overwrite existing chunks or not.
The MCA Selector has not been tested (by me) with mods, so i cannot guarantee its funtionality in that case. If those mods did not change the file format though, exporting, deleting and importing chunks should work fine as those functions do not touch the data in the chunks at all.
