### ISSUE TITLE
Bitdefender treats mcaselector as malware

### ISSUE THREAD

**Issue by sugar-peas** [Querz/mcaselector#176]
Bitdefender treats the application as a threat and keeps moving it to quarantine.

**Comment by hi5kba** [comment]
It’s a false flag, happens from time to time. More so as it seems that Microsoft is paying them off to flag anything that doesn’t come from their App Store as a threat. 

Easy fix for ya in the meantime. 

A) Add it to Anti-virus / ignore whitelist.
And / or B) switch to AVG or any other Antivirus software that isn’t only just in it for the Money.

kasperksy, bit defender and  Norton are all Premium only shit. unless your a Megacorperation totally not worth the price. They even accept payoffs to get stuff omitted from being registered as viruses.

Hell they’re practically spyware themselves. AVs shouldn’t need total Kernal access.

**Comment by Querz** [comment]
I assume it is treated as malware because the installer is (currently) not signed. I tested this a little bit, and it appears that some antivirus software doesn't like it when it's not signed. Some antivirus software even accepts it if i use a self-signed certificate i made and applied to the installer with literally 2 PowerShell commands.

See here:
[Not signed](https://www.virustotal.com/gui/file/dc6488070b479797c466114af8e349ee135fa52223d8262c68198c7b881f5df6/detection)
[Signed with 2-PowerShell-commands-certificate](https://www.virustotal.com/gui/file/f0df52a959b26f5cd5364c39ce058730b89dd0319a5286c4f009fb498b8a2aef/detection)

Signing the installation package properly is not a priority right now, maybe i can do that sometime in the future. Until then, just tell Bitdefender to ignore it.
