### ISSUE TITLE
[Feature Request] Scaling options when zooming in

### ISSUE THREAD

**Issue by BillerNET** [Querz/mcaselector#204]
Could you consider adding an option to set the zoom scale mode to either smoothing (current) or nearest-neighbour. Nearest-neighbour would reduce blurring when zooming in.

![Currrent zoomed image on left. Manually scaled on the right](https://user-images.githubusercontent.com/4222861/120068645-9cd96200-c079-11eb-88a5-1787b1fdb011.png)

**Comment by Querz** [comment]
I had this on the radar for quite some time, but due to restrictions in JavaFX 8 it was difficult to do. [Alongside Minecraft](https://minecraft.fandom.com/wiki/Java_Edition_21w19a), i will update to Java 16 though, which will make this easily configurable. In fact, the [java16](https://github.com/Querz/mcaselector/tree/java16) branch already has this feature if you would like to test it.

**Comment by Querz** [comment]
Added in [release 1.16](https://github.com/Querz/mcaselector/releases/tag/1.16).
