### ISSUE TITLE
BUG: Up Arrow key stays active once prossed

### ISSUE THREAD

**Issue by narcarsiss** [Querz/mcaselector#229]
Once you open a world in MCA Selector and hit the `Up arrow key`  Upwards scrolling moves infinitely.

There is no way to prevent or stop it other than to close MCA Selector.

Tried, Escape, Down Arrow, Up Arrow again, Shift, Control and Enter.

**Comment by Querz** [comment]
Fixed in [release 1.16.3](https://github.com/Querz/mcaselector/releases/tag/1.16.3). The up-arrow key caused the map view to lose focus and switch to the height slider, so it would never catch the key release event.
The arrow keys will not cause the focus the change anymore. The focus can still be changed with the `Tab` key though.
