### ISSUE TITLE
New generated chunks aren't shown properly 

### ISSUE THREAD

**Issue by beypazari** [Querz/mcaselector#244]
**Describe the bug**
The chunks that are new generated ( the world should be opened on MCA Selector before ) aren't shown properly. The bug doesn't occur when you delete the files on `%LOCALAPPDATA%\mcaselector\cache`

**To Reproduce**
1. Create a new world on Minecraft / Run existing world
2. Open the world once on MCA Selector
3. Go back to Minecraft and generate new chunks
4. Reopen the world on MCA Selector and the bug will occur.

**Expected behavior**
New generated chunks would be shown properly

**Screenshots and other files**
[A newly created world on MCA ](https://i.imgur.com/gjpzp4Y.png)
[The same world on MCA after generating new chunks](https://i.imgur.com/MJjqpoH.png)
[The same world on MCA after deleting the files on `%LOCALAPPDATA%\mcaselector\cache` ](https://i.imgur.com/I19PUxG.png)

**Environment (please complete the following information):**
- OS: Windows 10
- Java version: 1.7.4 ( occurs on any version )
- Version of MCA Selector 1.16.3

**Additional context**
None

**Comment by Querz** [comment]
Currently MCA Selector does not recognize when an mca file has been modified. I was thinking about using the cache database (that is currently only used for overlay data) to keep track of this.

I will rephrase this into a feature request, because this has been asked before.

For now you can use the `View --> Clear all cache` to delete the entire cache or either `View --> Clear cache` to only clear the cache of all regions in the viewport or `Selection --> Clear cache` to clear the cache of all regions in the selection.

**Comment by Querz** [comment]
In [release 1.17](https://github.com/Querz/mcaselector/releases/latest) MCA Selector now detects region file changes whenever attempting to load cached image files (which means when loading a world). This can be triggered manually by pressing `F5`.
