### ISSUE TITLE
World made in 21w37a doesn't render

### ISSUE THREAD

**Issue by boasbakker** [Querz/mcaselector#254]
When I load a world made in 21w37a everything is black.

1. Create a world in the newest snapshot
2. Open it in MCAselector
3. Everything is black

**Expected behavior**
I expected it to show a map of the world

**Screenshots and other files**
[debug.log](https://github.com/Querz/mcaselector/files/7204903/debug.log)

**Environment:**
- OS: Windows 10
- Java version: 16.0.1
- MCA Selector version: 1.16.3 and 1.16.2

**Comment by SansQuartier** [comment]
I have the exact same problems with portions of a map saved from a server with a mod.
The world won't load either using Amulet.

**Comment by boasbakker** [comment]
It seems like the way chunks sections are stored is different then 1.18 experimental snapshot 7. 
In that version MCAselector worked fine. 
I don't think this is too hard to fix, because when I loaded up the chunk data in NBTexplorer it seemed almost the same as in 1.18 experimental snapshot 7. 
I also tried downgrading an 21w37a world to 1.18 experimental snapshot 7, and the whole world became void (all previously generated chunks). Biomes and entities remained. 
Also, fabric mods that do things with maps also don't work for this snapshot. This all led me to conclidude that there must have been a change since experimental snapshot 7 in the way sections are stored.

**Comment by Querz** [comment]
The 1.18 snapshots are currently not supported. I had a look at what they changed in 21w37a, and it seems they are migrating to a more cubic approach for chunks.

Mojang seems to have decided to save biomes on the Sections level instead of the chunk level and they introduced a biome palette (similar to the palette for block states):

![image](https://user-images.githubusercontent.com/8278330/134411708-60132239-5e52-4b87-81a5-203099e9d16a.png)

They also moved the block states into a new CompoundTag called `block_states`, so MCA Selector thinks the sections don't have any blocks because it doesn't know about  this change.

Updating this shouldn't be too difficult.

**Comment by boasbakker** [comment]
Very interesting. So you are gonna update the program so it works with the snapshot? That would be amazing. I am running a survival server with some friends on the latest snapshot, and sometimes we want to remove some chunks to have newer terrain closer to spawn. Each time we update to a new snapshot we do that. So I useMCAselector, and it would be handy if it would work for this snashot

**Comment by Querz** [comment]
Support for rendering up to 21w43a has been added in [release 1.17](https://github.com/Querz/mcaselector/releases/latest).
