### ISSUE TITLE
Selection Invert is VERY bugged

### ISSUE THREAD

**Issue by Jordan231111** [Querz/mcaselector#275]
When selecting invert chunks, **it inverts to infinity chunks instead of the chunks that have been explored** leading to infinite hang time and just the whole software malfunctioning when trying to delete chunks.

**Comment by Matej-Hajek** [comment]
Agreed, I think it only selects chunks that can be seen. And it would be great if some error appeared when all regions are selected while inverting.

*I think it should behave like this:*
- *the program only selects generated regions(compares selected regions with regions in the `region` folder of the current dimension)*

**Comment by Querz** [comment]
Creating a selection and then inverting it technically only sets a flag to render the entire selection inverted (the data in memory that represents the selection does not change, it is just rendered differently). Only when it has to do something with that selection (specifically deleting, importing or exporting chunks) it will create an inverted version of that data structure, based on all existing region files in the `region`, `poi` and `entities` folders (so in other words, it does exactly what @Matej-Hajek is describing, just not at the point in time when the selection is inverted visually).

Saying that this process is "leading to infinite hang time and just the whole software malfunctioning when trying to delete chunks" does not help me figuring out what the problem is. There is a [bug report template](https://github.com/Querz/mcaselector/issues/new?assignees=&labels=&template=bug_report.md&title=) for a reason, please use it to report bugs in a way i can reproduce them. Thank you.
