### ISSUE TITLE
[enhancement] add a feature that allows to reset biomes to default. [1.18-1.19]

### ISSUE THREAD

**Issue by Lolothepro** [Querz/mcaselector#351]
[enhancement] add a feature that allows to reset biomes to default.

**Comment by Querz** [comment]
Unfortunately, biomes in Minecraft 1.19. and 1.19 can't be reset to default by simply changing the biome in the mca files to and invalid value anymore. Minecraft will only set it to *the* default biome (plains). Changing the chunk `Status` to `biomes` is also not an option, because biomes are generated before the terrain. Doing that would force Minecraft to regenerate the terrain ontop of any already existing terrain and overwrite any player-made structures.
