### ISSUE TITLE
Chunk info. 

### ISSUE THREAD

**Issue by lantren** [Querz/mcaselector#41]
It would be very useful to have a get a chunk info menu item. That way one does not have to resort to another program or viewer to view NBT data.

**Comment by SteliosLL** [comment]
Put this to the pull requests

**Comment by Querz** [comment]
What kind of chunk info did you have in mind and how should this information be displayed?

**Comment by lantren** [comment]
I guess to start with, having the  "Change fields.."  dialog be pre-populated with the current NBT data would be nice.  That could also part of a general info dialog box.  A list of entities may be interesting,  albeit just informational.

**Comment by Querz** [comment]
I've been playing around with this for a bit, and this is what I came up with:
![Screenshot 2019-09-26 at 14 12 34](https://user-images.githubusercontent.com/8278330/65687721-1ed5e400-e06a-11e9-8346-3da25753571e.png)
* The values are visible as a hint text (not editable). Only edited values will actually be touched in the chunk data.
* "Biome" does not show anything, because a chunk could theoretically have up to 256 different biomes. As stated in the Readme, setting the biome here sets the biomes for the entire chunk.
* "Apply to selection only" is selected by default.
* If a field does not exist in the chunk data, no hint is shown (e.g. the "Status" field does not exist in Minecraft before 1.13).
* There is no guarantee that these values are shown, because the top-down view of the map might not be up to date with the actual existing chunks and regions.
* These values are only shown when a *single* chunk is selected. Selecting more than one or none, will not show any values.

I will look more into making a "general information" dialog. This dialog would have the same restriction as the "change nbt" dialog though and only show data of a single selected chunk for now.

**Comment by Querz** [comment]
[Release 1.9](https://github.com/Querz/mcaselector/releases) shows the values currently saved in the chunk in the "Change NBT" dialog, when only a single chunk is selected. I also added a simple NBT editor to the "Tools" menu. This options becomes available when only a single chunk is selected. You can add, delete, move (drag+drop) and edit names and values of the NBT structure.
