### ISSUE TITLE
Filtering chunks - add option to preserve X chunks around to make more nicer map trim

### ISSUE THREAD

**Issue by Fixer-007** [Querz/mcaselector#71]
Idea is simple: say you want to trim a map by keeping only chunks with some torches/cobblestone/othersignsofhumans, you do usual "Filter chunks" -> by torch/cobble, BUT, you also set "preserve X chunks away around each filtered block", so when initial filtering is done it increases preservation area so you don't have issues like missing chunk in a middle of your base or some roads.

For example, if you set preserve to 1 chunk away, it will be this (C is block with torch, P - preserve)
~~~
P P P
P C P
P P P
~~~
when set to 2 chunks away
~~~
P P P P P
P P P P P
P P C P P
P P P P P
P P P P P
~~~

After that you "Export selected chunks" to a new folder and enjoy better seamlessly preserved world.

For example in this screenshot there are some gaps that can be preserved via this new option:
![зображення](https://user-images.githubusercontent.com/16494741/73123831-e81ec480-3f9c-11ea-871e-f810790d6fe1.png)

**Comment by Querz** [comment]
This could work for selecting chunks, but for deleting and exporting based on the filter directly would be difficult.
To make the export and the deletion faster, regions are loaded into memory and processed concurrently in multiple independent threads. There is no connection between them so exporting or deleting chunks with a radius past the region border does not work.
This can work for selections though, because a selection is kept in memory. The selection could then be used to export or delete those chunks.

**Comment by Querz** [comment]
Added this feature in [release 1.9.4](https://github.com/Querz/mcaselector/releases/tag/1.9.4) for selecting chunks using the chunk filter.
