### ISSUE TITLE
Cannot change nether biomes

### ISSUE THREAD

**Issue by jorbeee** [Querz/mcaselector#93]
**Describe the bug**
I selected chunks in the nether file and change it to "nether_wastes", i open the save file in Minecraft, biome has not changed

**To Reproduce**
1. select chunks
2. click tools
3. Scroll down to "change fields", opens "Change NBT"
4. enter "nether_wastes" in "Biome"
5. then open Minecraft, no biome has changed

**Expected behavior**
I expected the selected chunks to have their biomes changed

**Environment (please complete the following information):**
- OS: Windows 10 Pro
- Java version: newest version

**Additional context**
Add any other context about the problem here, e.g.:
- Minecraft version 1.15.2, but i updated game to newest snapshot

**Comment by Querz** [comment]
What is the biome that you want to overwrite?

**Comment by jorbeee** [comment]
Warped forest

**Comment by jorbeee** [comment]
Also, is there a way to change what I see on the map, all I mainly see is nether ceiling, https://imgur.com/jlQd6Sn is there a way to change or fix this

**Comment by Querz** [comment]
Since 19w36a (1.15 Snapshot) instead of saving biomes per block column (every block with the same y-coordinate having the same biome), they are saving a biome per 4x4x4 area now, which technically allows to have multiple biomes vertically.

It appears that Minecraft now somehow makes biome borders "smooth" or blends them together in game (?). Here an example (Snapshot 20w16a):

This is a corner of a chunk in the middle of a warped_forest biome, as seen in the F3 screen.
<img width="966" alt="Screenshot 2020-04-20 at 12 08 44" src="https://user-images.githubusercontent.com/8278330/79741229-2e1bc800-8301-11ea-9c6a-55f10b054823.png">
Selected that chunk in MCA Selector:
<img width="912" alt="Screenshot 2020-04-20 at 12 10 06" src="https://user-images.githubusercontent.com/8278330/79741335-5d323980-8301-11ea-8dab-ddb929e624a0.png">
And used the NBT Changer to change all biomes to nether_wastes (ID 8). Checked the NBT Editor to make sure they are all set correctly:
<img width="316" alt="Screenshot 2020-04-20 at 12 11 04" src="https://user-images.githubusercontent.com/8278330/79741449-92d72280-8301-11ea-9e4f-1ac0d25d2062.png">
Now, back in Minecraft. When I move up or down at the same location as before, it sometimes shows nether_wastes OR warped_forest (notice the x- and z-coordinates staying the same):
<img width="966" alt="Screenshot 2020-04-20 at 12 12 41" src="https://user-images.githubusercontent.com/8278330/79741616-d9c51800-8301-11ea-8256-8c91ee8c9907.png">
<img width="966" alt="Screenshot 2020-04-20 at 12 12 55" src="https://user-images.githubusercontent.com/8278330/79741641-e21d5300-8301-11ea-9bb7-c63ed5037aa6.png">

I can't really do anything about that, sorry. MCA Selector only manipulates the data in mca files :)
---
About the Nether not rendering correctly: Usually, all standard blocks are ignored (specifically bedrock, lava, netherrack and nether_quartz_ore) down to a depth of 75. I already added a fix where basalt will also be ignored, which will be in the next release.

**Comment by Querz** [comment]
I assume that all questions are answered and this is resolved.
