### ISSUE TITLE
Scales improperly when moving window to another monitor

### ISSUE THREAD

**Issue by nicholasz2510** [Querz/mcaselector#97]
**Describe the bug**
If the window is dragged to a separate monitor of the same resolution but with a different scale, the scale of the toolbars is off. 

**To Reproduce**
1. Have two displays with the same resolution but different scale configured to extend the screen
2. Run MCA Selector
3. Drag the window to the other monitor

**Expected behavior**
The toolbars should scale as they do with other modern applications with similar bars at the top and bottom.

**Screenshots**
What it should look like:
![image](https://user-images.githubusercontent.com/20385225/80899105-3abcfa80-8cc9-11ea-8749-f9ef5a50f4e4.png)
What it looks like on the secondary monitor: (Notice that the Chrome tab size gets taller and scales but the toolbar is still thin)
![image](https://user-images.githubusercontent.com/20385225/80899116-56c09c00-8cc9-11ea-8599-02eb72dec9aa.png)

**Environment:**
- OS: Windows 10
- Java version: 1.8.0_241-b07
- Version: 1.9.4

**Additional context**
The primary monitor is 21.5 inches, and the secondary monitor is 15.6 inches

**Comment by Querz** [comment]
I can't really reproduce this as i don't have the specific screen setup 😅 , but i tried changing the scale on Windows 10 running in a VM while MCA Selector was open.
So that's what happened:
Using a Windows 10 VM on a Windows Host: Scaling to 125% did not change the size of the menus compared to 100%, but scaling to 150% did.
Using a Windows 10 VM on a Mac Host: Scaling works flawlessly with every scale setting.
So I don't really know what causes this, maybe Windows 10 scaling behaves differently with different screen resolutions (?)

In any case this is tied to the implementation of Java on Windows and Windows itself, and I cannot really do anything about this. JavaFX is supposed to scale automatically (which it does in most cases), but i have no idea why it sometimes doesn't.
