### ISSUE TITLE
1.16 breaks rendering with slight changes to save format

### ISSUE THREAD

**Issue by chexbox** [Querz/mcaselector#99]
When opening a world from the latest snapshots, many chunks are only partially displayed. This looks somewhat similar to #65 

Here's a screenshot
![Screenshot from 2020-05-06 15-09-42](https://user-images.githubusercontent.com/31783961/81223653-f624ae00-8fab-11ea-990d-55af591aa38d.png)

**Comment by Querz** [comment]
Make sure to use the [latest version 1.9.10](https://github.com/Querz/mcaselector/releases/latest), as it adds support for the new blockstates format introduced in 20w17a.
I am aware that the "About" dialog does not show 1.9.10 as the next available version, because the version checking only does a String comparison which puts 1.9.10 alphabetically behind 1.9.9. This will be fixed in the next release.

**Comment by chexbox** [comment]
Oh, I tried 1.9.10 earlier and thought it wasn't fixed because it was still cached. Clearing the cache seemed to fix it.
